language: generic
os: linux
dist: trusty
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.ccache
matrix:
  fast_finish: true
env:
  - DOCKER_TAG=latest QMAKE_SPEC=linux-g++
  - DOCKER_TAG=devel QMAKE_SPEC=linux-g++
  - DOCKER_TAG=trusty QMAKE_SPEC=linux-g++

before_install:
  - export DOCKER_FILE="./${DOCKER_TAG}/Dockerfile"
  - export DOCKER_IMAGE="librepcb/librepcb:${DOCKER_TAG}"
  - export LIBREPCB_DIR="${HOME}/librepcb"

install:
  - git clone --recursive -b use_docker_for_ci https://github.com/LibrePCB/LibrePCB.git ${LIBREPCB_DIR}

script:
  - docker build -t ${DOCKER_IMAGE} -f ${DOCKER_FILE} .
  - docker run -it -e QMAKE_SPEC=${QMAKE_SPEC} -v ${LIBREPCB_DIR}:/librepcb -v $HOME/.ccache:/ccache
    --entrypoint="entrypoint.sh" ${DOCKER_IMAGE} sh -c "cd /librepcb/dev/ci && ./build.sh && ./test.sh"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ${DOCKER_IMAGE};
    fi

notifications:
  email:
    on_success: change
    on_failure: change
