FROM ubuntu:14.04

RUN apt-get update && apt-get -y install --no-install-recommends \
    g++ \
    git \
    libglu1-mesa-dev \
    qt5-default \
    qttools5-dev-tools \
  && rm -rf /var/lib/apt/lists/*
